apiVersion: v1
kind: Service
metadata:
  name: service-track-bff
  labels:
    app: service-track-bff
spec:
  type: ClusterIP
  selector:
    app: service-track-bff
  ports:
    - name: http
      port: 80
      targetPort: 8080
