servicetrack:
  usuarios:
    base-url: nao-usado-no-perfil-dev
  catalogo:
    base-url: nao-usado-no-perfil-dev
  ordens:
    base-url: nao-usado-no-perfil-dev
  security:
    jwt:
      enabled: false

logging:
  structured:
    format:
      console:
  level:
    com.clau.service_track.bff: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
